# Generated by Django 5.1.6 on 2025-04-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextgrowthbaseuser',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Dev', 'Developer')], db_index=True, default='User', max_length=10, verbose_name='User Type'),
        ),
    ]
