# Generated by Django 5.1.6 on 2025-04-05 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_alter_nextgrowthbaseuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='nextgrowthbaseuser',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Dev', 'Developer'), ('Other', 'Other')], db_index=True, default='User', max_length=10, verbose_name='User Type'),
        ),
    ]
