# Generated by Django 5.1.6 on 2025-04-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_tasksubmission_created_at_tasksubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextgrowthbaseuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
