# Generated by Django 5.1.6 on 2025-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_rename_profile_pic_nextgrowthbaseuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='user_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
