# Generated by Django 5.1.6 on 2025-04-08 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_tasksubmission_user_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptask',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nextgrowthbaseuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
